In [1]:
import numpy as np

In [2]:
list = [2,4,56,422,32,1]

In [3]:
list

[2, 4, 56, 422, 32, 1]

In [6]:
arr = np.array(list)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([  2,   4,  56, 422,  32,   1])

2D array (matrix)

In [9]:
new = np.array([[45,34,22,2],[24,55,3,22]])

In [10]:
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [11]:
##3D array--------# Tensor

In [21]:
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [22]:
np.array([11,23,44], dtype=float)

array([11., 23., 44.])

In [23]:
np.array([11,23,44],dtype=float)

array([11., 23., 44.])

In [24]:
np.array([11,23,44],dtype=bool)

array([ True,  True,  True])

In [25]:
np.array([11,23,44],dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

arange 
arrange can be called with a varying number of positional argument

In [27]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
np.arange(1,25,2 #strides ---> Alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

reshape:-
both the number product should be equal to umber of items presnt inside the array

In [32]:
np.arange(1,11).reshape(5,2) #convert 5 row and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [33]:
np.arange(1,11).reshape(2,5) #convert 2 row and 5columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
np.arange(1,13).reshape(3,4) #convert 3 row and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

one and zero

In [1]:
#np.once and #np.zero

In [7]:
import numpy as np
np.ones((3,4)) #we have to mention inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((3,4))

array([[0.1923331 , 0.14958771, 0.90594661, 0.6162523 ],
       [0.67873393, 0.46915509, 0.43465981, 0.58349946],
       [0.27639471, 0.97988597, 0.54012599, 0.39326115]])

In [15]:
#linspace:-It is also called as Linearly space , Linearly separable,in a given range at equal distance it creates points. 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

identity:-indentity matrix is that diagonal items will be ones and evrything will be zeros

In [17]:
#create the identy metrix

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Array attribute

In [20]:
a1= np.arange(10)

In [21]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(12, dtype=float).reshape(3,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])